spring:
  datasource:
    druid:
      url: jdbc:mysql://123.207.64.215:3306/michat?useUnicode=true&characterEncoding=UTF-8
      username: ttsource
      password: al2cdIk3M9vj58j+2ldk7/UhgfnqTXOpGd9nT3CB4uq8HKhwMUBLABpX1bAZSJysJbZZ7GwMy6WvvHpiRZCpqQ==
      driver-class-name: com.mysql.jdbc.Driver
      db-type: com.alibaba.druid.pool.DruidDataSource
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        commons-log:
          connection-logger-name: stat,wall,log4j
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
          merge-sql: true
        # 启动ConfigFilter
        config:
          enabled: true
      use-global-data-source-stat: true
      connection-properties: config.decrypt=true;config.decrypt.key=${publickey}
  redis:
    host: 123.207.64.215
    port: 6379
    database: 0
    password: redis
  devtools:
    restart:
      enabled: true
      exclude: WEB-INF/**
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 1MB
      max-request-size: 3MB
      resolve-lazily: false
mybatis:
  type-aliases-package: com.ttsource.mapper
  mapper-locations: classpath:mapper/*.xml
server:
  ssl:
    key-store: classpath:michat.jks
    key-store-password: 123456
environment:
  release: true
  jwt:
    header: Authorization
    head: MiChatHeader#_
publickey:
  MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJUk82FWBNIwXZEGMtVr0PT8KAOjKuNiW9GAU5qASPVF12iryhV0jVJOu8mgrpv1Cgy1jLchffdeYNjtWcxPSeMCAwEAAQ==