spring:
  datasource:
    druid:
      url: jdbc:mysql://116.228.75.54:9901/qpgis-monitor?useUnicode=true&characterEncoding=UTF-8
      username: sa
      password: Sa@1234567890
      driver-class-name: com.mysql.jdbc.Driver
      db-type: com.alibaba.druid.pool.DruidDataSource
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        commons-log:
          connection-logger-name: stat,wall,log4j
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
          merge-sql: true
        # 启动ConfigFilter
        config:
          enabled: true
  redis:
    host: 116.228.75.54
    port: 6379
    database: 0
    password: Sa@1234567890
  devtools:
    restart:
      enabled: true
      exclude: WEB-INF/**
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 1MB
      max-request-size: 3MB
      resolve-lazily: false
mybatis:
  type-aliases-package: com.ttsource.mapper
  mapper-locations: classpath:mapper/*.xml
server:
  ssl:
    key-store: classpath:michat.jks
    key-store-password: 123456
environment:
  release: false
  jwt:
    header: Authorization
    head: MiChatHeader#_